[package]
name = "good_vibes"
version = "0.1.0"
authors = ["Walter Sharp"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
reqwest = "0.9.1"